USE [master]
GO

/****** Object:  Database [finch_inventory]    Script Date: 12/20/2018 6:17:25 PM ******/
CREATE DATABASE [finch_inventory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'finch_inventory', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\finch_inventory.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'finch_inventory_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\finch_inventory_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [finch_inventory] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [finch_inventory].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [finch_inventory] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [finch_inventory] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [finch_inventory] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [finch_inventory] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [finch_inventory] SET ARITHABORT OFF 
GO

ALTER DATABASE [finch_inventory] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [finch_inventory] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [finch_inventory] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [finch_inventory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [finch_inventory] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [finch_inventory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [finch_inventory] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [finch_inventory] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [finch_inventory] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [finch_inventory] SET  DISABLE_BROKER 
GO

ALTER DATABASE [finch_inventory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [finch_inventory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [finch_inventory] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [finch_inventory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [finch_inventory] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [finch_inventory] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [finch_inventory] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [finch_inventory] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [finch_inventory] SET  MULTI_USER 
GO

ALTER DATABASE [finch_inventory] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [finch_inventory] SET DB_CHAINING OFF 
GO

ALTER DATABASE [finch_inventory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [finch_inventory] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [finch_inventory] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [finch_inventory] SET QUERY_STORE = OFF
GO

ALTER DATABASE [finch_inventory] SET  READ_WRITE 
GO

